import type { Meta, StoryObj } from '@storybook/react';
import CardList from '../../components/CardList';

const meta = {
  title: 'Component/CardList',
  component: CardList,
  parameters: {
    layout: 'centered',
  },
} satisfies Meta<typeof CardList>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    cards: [
      {
        id: 1,
        name: 'The Fool',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg',
        rarity: 'epic',
      },
      {
        id: 2,
        name: 'The Magician',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg',
        rarity: 'epic',
      },
      {
        id: 3,
        name: 'The High Priestess',
        imageURL:
          'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg',
        rarity: 'epic',
      },
      {
        id: 4,
        name: 'The Empress',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg',
        rarity: 'epic',
      },
      {
        id: 5,
        name: 'The Emperor',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg',
        rarity: 'epic',
      },
      {
        id: 6,
        name: 'The Hierophant',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg',
        rarity: 'epic',
      },
      {
        id: 7,
        name: 'The Lovers',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_06_Lovers.jpg',
        rarity: 'epic',
      },
      {
        id: 8,
        name: 'The Chariot',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg',
        rarity: 'epic',
      },
      {
        id: 9,
        name: 'Strength',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg',
        rarity: 'epic',
      },
      {
        id: 10,
        name: 'The Hermit',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg',
        rarity: 'epic',
      },
      {
        id: 11,
        name: 'Wheel of Fortune',
        imageURL:
          'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',
        rarity: 'epic',
      },
      {
        id: 12,
        name: 'Justice',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg',
        rarity: 'epic',
      },
      {
        id: 13,
        name: 'The Hanged Man',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg',
        rarity: 'epic',
      },
      {
        id: 14,
        name: 'Death',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg',
        rarity: 'epic',
      },
      {
        id: 15,
        name: 'Temperance',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg',
        rarity: 'epic',
      },
      {
        id: 16,
        name: 'The Devil',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg',
        rarity: 'epic',
      },
      {
        id: 17,
        name: 'The Tower',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg',
        rarity: 'epic',
      },
      {
        id: 18,
        name: 'The Star',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg',
        rarity: 'epic',
      },
      {
        id: 19,
        name: 'The Moon',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg',
        rarity: 'epic',
      },
      {
        id: 20,
        name: 'The Sun',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg',
        rarity: 'epic',
      },
      {
        id: 21,
        name: 'Judgment',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg',
        rarity: 'epic',
      },
      {
        id: 22,
        name: 'The World',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg',
        rarity: 'epic',
      },
      {
        id: 23,
        name: 'Ace of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg',
        rarity: 'normal',
      },
      {
        id: 24,
        name: 'Two of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg',
        rarity: 'normal',
      },
      {
        id: 25,
        name: 'Three of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg',
        rarity: 'normal',
      },
      {
        id: 26,
        name: 'Four of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg',
        rarity: 'normal',
      },
      {
        id: 27,
        name: 'Five of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg',
        rarity: 'normal',
      },
      {
        id: 28,
        name: 'Six of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg',
        rarity: 'normal',
      },
      {
        id: 29,
        name: 'Seven of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg',
        rarity: 'normal',
      },
      {
        id: 30,
        name: 'Eight of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg',
        rarity: 'normal',
      },
      {
        id: 31,
        name: 'Nine of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg',
        rarity: 'normal',
      },
      {
        id: 32,
        name: 'Ten of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg',
        rarity: 'normal',
      },
      {
        id: 33,
        name: 'Page of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg',
        rarity: 'rare',
      },
      {
        id: 34,
        name: 'Knight of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg',
        rarity: 'rare',
      },
      {
        id: 35,
        name: 'Queen of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg',
        rarity: 'rare',
      },
      {
        id: 36,
        name: 'King of Wands',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg',
        rarity: 'rare',
      },
      {
        id: 37,
        name: 'Ace of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg',
        rarity: 'normal',
      },
      {
        id: 38,
        name: 'Two of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg',
        rarity: 'normal',
      },
      {
        id: 39,
        name: 'Three of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg',
        rarity: 'normal',
      },
      {
        id: 40,
        name: 'Four of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg',
        rarity: 'normal',
      },
      {
        id: 41,
        name: 'Five of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg',
        rarity: 'normal',
      },
      {
        id: 42,
        name: 'Six of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg',
        rarity: 'normal',
      },
      {
        id: 43,
        name: 'Seven of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg',
        rarity: 'normal',
      },
      {
        id: 44,
        name: 'Eight of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg',
        rarity: 'normal',
      },
      {
        id: 45,
        name: 'Nine of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg',
        rarity: 'normal',
      },
      {
        id: 46,
        name: 'Ten of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg',
        rarity: 'normal',
      },
      {
        id: 47,
        name: 'Page of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg',
        rarity: 'rare',
      },
      {
        id: 48,
        name: 'Knight of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg',
        rarity: 'rare',
      },
      {
        id: 49,
        name: 'Queen of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg',
        rarity: 'rare',
      },
      {
        id: 50,
        name: 'King of Cups',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg',
        rarity: 'rare',
      },
      {
        id: 51,
        name: 'Ace of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg',
        rarity: 'normal',
      },
      {
        id: 52,
        name: 'Two of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg',
        rarity: 'normal',
      },
      {
        id: 53,
        name: 'Three of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg',
        rarity: 'normal',
      },
      {
        id: 54,
        name: 'Four of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg',
        rarity: 'normal',
      },
      {
        id: 55,
        name: 'Five of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg',
        rarity: 'normal',
      },
      {
        id: 56,
        name: 'Six of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg',
        rarity: 'normal',
      },
      {
        id: 57,
        name: 'Seven of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg',
        rarity: 'normal',
      },
      {
        id: 58,
        name: 'Eight of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg',
        rarity: 'normal',
      },
      {
        id: 59,
        name: 'Nine of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg',
        rarity: 'normal',
      },
      {
        id: 60,
        name: 'Ten of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg',
        rarity: 'normal',
      },
      {
        id: 61,
        name: 'Page of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg',
        rarity: 'rare',
      },
      {
        id: 62,
        name: 'Knight of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg',
        rarity: 'rare',
      },
      {
        id: 63,
        name: 'Queen of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg',
        rarity: 'rare',
      },
      {
        id: 64,
        name: 'King of Swords',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg',
        rarity: 'rare',
      },
      {
        id: 65,
        name: 'Ace of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg',
        rarity: 'normal',
      },
      {
        id: 66,
        name: 'Two of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg',
        rarity: 'normal',
      },
      {
        id: 67,
        name: 'Three of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg',
        rarity: 'normal',
      },
      {
        id: 68,
        name: 'Four of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg',
        rarity: 'normal',
      },
      {
        id: 69,
        name: 'Five of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg',
        rarity: 'normal',
      },
      {
        id: 70,
        name: 'Six of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg',
        rarity: 'normal',
      },
      {
        id: 71,
        name: 'Seven of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg',
        rarity: 'normal',
      },
      {
        id: 72,
        name: 'Eight of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg',
        rarity: 'normal',
      },
      {
        id: 73,
        name: 'Nine of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg',
        rarity: 'normal',
      },
      {
        id: 74,
        name: 'Ten of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg',
        rarity: 'normal',
      },
      {
        id: 75,
        name: 'Page of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg',
        rarity: 'rare',
      },
      {
        id: 76,
        name: 'Knight of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg',
        rarity: 'rare',
      },
      {
        id: 77,
        name: 'Queen of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg',
        rarity: 'rare',
      },
      {
        id: 78,
        name: 'King of Pentacles',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg',
        rarity: 'rare',
      },
    ],
  },
};
